/*
 * Copyright 2015-2026 Ritense BV, the Netherlands.
 *
 * Licensed under EUPL, Version 1.2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ritense.valtimoplugins.xential.web.rest

import com.ritense.valtimo.contract.annotation.SkipComponentScan
import com.ritense.valtimo.contract.domain.ValtimoMediaType
import com.ritense.valtimoplugins.xential.domain.DocumentCallbackOutcome
import com.ritense.valtimoplugins.xential.domain.DocumentCreatedMessage
import com.ritense.valtimoplugins.xential.service.DocumentGenerationService
import com.ritense.valtimoplugins.xential.service.XentialCallbackVerificationService.Companion.SIGNATURE_HEADER
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestHeader
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

@RestController
@SkipComponentScan
@RequestMapping("/api", produces = [ValtimoMediaType.APPLICATION_JSON_UTF8_VALUE])
class DocumentResource(
    val documentGenerationService: DocumentGenerationService,
) {
    /**
     * Receives the content of a document generated by Xential.
     *
     * Every response has an empty body, and every way of failing to identify a live document creation session
     * shares one status code, so that an unauthenticated caller learns nothing about which session ids exist.
     */
    @PostMapping("/v1/xential/document")
    fun handleSubmission(
        @RequestBody message: DocumentCreatedMessage,
        @RequestHeader(name = SIGNATURE_HEADER, required = false) signature: String?,
    ): ResponseEntity<Unit> =
        when (documentGenerationService.onDocumentGenerated(message, signature)) {
            DocumentCallbackOutcome.PROCESSED -> ResponseEntity.ok().build()
            DocumentCallbackOutcome.INVALID_SIGNATURE -> ResponseEntity.status(HttpStatus.UNAUTHORIZED).build()
            DocumentCallbackOutcome.INVALID_REQUEST -> ResponseEntity.status(HttpStatus.NOT_FOUND).build()
            DocumentCallbackOutcome.RATE_LIMITED -> ResponseEntity.status(HttpStatus.TOO_MANY_REQUESTS).build()
        }
}
